###
Going into loop now
###
###
Using config file /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_HH.txt...
###
docker run -it --rm --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" --volume="/etc/sudoers.d:/etc/sudoers.d:ro" --volume="/:/host:rw" --volume="/data3/nadeem/GitHub:/home/nadeem/GitHub:rw" --volume="/data3/nadeem/rfi-chronicles:/home/nadeem/rfi-chronicles:rw" --volume="/data3/nadeem/KATHPRFI/RDB_FILES:/home/nadeem/KATHPRFI/RDB_FILES:rw" --volume="/data3/nadeem/KATHPRFI/FLAG_FILES:/home/nadeem/KATHPRFI/FLAG_FILES:rw" --volume="/data3/nadeem/KATHPRFI/OUT_ZARR:/home/nadeem/KATHPRFI/OUT_ZARR:rw" --volume="/data3/nadeem/KATHPRFI/GOOD_FILES:/home/nadeem/KATHPRFI/GOOD_FILES:rw" --volume="/data3/nadeem/KATHPRFI/BAD_FILES:/home/nadeem/KATHPRFI/BAD_FILES:rw" --volume="/tmp:/home/nadeem:rw" -e HOME="/home/nadeem" --user=1661 --net=host -e QT_X11_NO_MITSHM=1 -e DISPLAY=localhost:12.0 --volume="/home/nadeem/.Xauthority:/home/nadeem/.Xauthority" --volume="/home/nadeem/.Xdefaults:/home/nadeem/.Xdefaults" --name DOCKER_NAME kathprfidocker python3 /home/nadeem/GitHub/kathprfi/script/kathprfi_script.py -c /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_HH.txt -z /home/nadeem/KATHPRFI/OUT_ZARR/Uband_HH_.zarr -b /home/nadeem/KATHPRFI/BAD_FILES/bad_files_Uband_HH_2021FebSci.npy -g /home/nadeem/KATHPRFI/GOOD_FILES/good_files_Uband_HH_2021FebSci.npy
###
Using config file /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_VV.txt...
###
docker run -it --rm --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" --volume="/etc/sudoers.d:/etc/sudoers.d:ro" --volume="/:/host:rw" --volume="/data3/nadeem/GitHub:/home/nadeem/GitHub:rw" --volume="/data3/nadeem/rfi-chronicles:/home/nadeem/rfi-chronicles:rw" --volume="/data3/nadeem/KATHPRFI/RDB_FILES:/home/nadeem/KATHPRFI/RDB_FILES:rw" --volume="/data3/nadeem/KATHPRFI/FLAG_FILES:/home/nadeem/KATHPRFI/FLAG_FILES:rw" --volume="/data3/nadeem/KATHPRFI/OUT_ZARR:/home/nadeem/KATHPRFI/OUT_ZARR:rw" --volume="/data3/nadeem/KATHPRFI/GOOD_FILES:/home/nadeem/KATHPRFI/GOOD_FILES:rw" --volume="/data3/nadeem/KATHPRFI/BAD_FILES:/home/nadeem/KATHPRFI/BAD_FILES:rw" --volume="/tmp:/home/nadeem:rw" -e HOME="/home/nadeem" --user=1661 --net=host -e QT_X11_NO_MITSHM=1 -e DISPLAY=localhost:12.0 --volume="/home/nadeem/.Xauthority:/home/nadeem/.Xauthority" --volume="/home/nadeem/.Xdefaults:/home/nadeem/.Xdefaults" --name DOCKER_NAME kathprfidocker python3 /home/nadeem/GitHub/kathprfi/script/kathprfi_script.py -c /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_VV.txt -z /home/nadeem/KATHPRFI/OUT_ZARR/Uband_VV_.zarr -b /home/nadeem/KATHPRFI/BAD_FILES/bad_files_Uband_VV_2021FebSci.npy -g /home/nadeem/KATHPRFI/GOOD_FILES/good_files_Uband_VV_2021FebSci.npy
###
Using config file /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_HV.txt...
###
docker run -it --rm --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" --volume="/etc/sudoers.d:/etc/sudoers.d:ro" --volume="/:/host:rw" --volume="/data3/nadeem/GitHub:/home/nadeem/GitHub:rw" --volume="/data3/nadeem/rfi-chronicles:/home/nadeem/rfi-chronicles:rw" --volume="/data3/nadeem/KATHPRFI/RDB_FILES:/home/nadeem/KATHPRFI/RDB_FILES:rw" --volume="/data3/nadeem/KATHPRFI/FLAG_FILES:/home/nadeem/KATHPRFI/FLAG_FILES:rw" --volume="/data3/nadeem/KATHPRFI/OUT_ZARR:/home/nadeem/KATHPRFI/OUT_ZARR:rw" --volume="/data3/nadeem/KATHPRFI/GOOD_FILES:/home/nadeem/KATHPRFI/GOOD_FILES:rw" --volume="/data3/nadeem/KATHPRFI/BAD_FILES:/home/nadeem/KATHPRFI/BAD_FILES:rw" --volume="/tmp:/home/nadeem:rw" -e HOME="/home/nadeem" --user=1661 --net=host -e QT_X11_NO_MITSHM=1 -e DISPLAY=localhost:12.0 --volume="/home/nadeem/.Xauthority:/home/nadeem/.Xauthority" --volume="/home/nadeem/.Xdefaults:/home/nadeem/.Xdefaults" --name DOCKER_NAME kathprfidocker python3 /home/nadeem/GitHub/kathprfi/script/kathprfi_script.py -c /home/nadeem/KATHPRFI/RDB_FILES/kathprfi_config_SCI_Imaging_U_2021-02-01_2021-02-28_HV.txt -z /home/nadeem/KATHPRFI/OUT_ZARR/Uband_HV_.zarr -b /home/nadeem/KATHPRFI/BAD_FILES/bad_files_Uband_HV_2021FebSci.npy -g /home/nadeem/KATHPRFI/GOOD_FILES/good_files_Uband_HV_2021FebSci.npy
